name: 'OIDC Debug'
description: 'OIDC Debug'
author: 'qoomon'
branding:
  icon: box
  color: blue

inputs:
  oidc-token:
    description: 'An OIDC token'

runs:
  using: 'node20'
  main: 'dist/index.js'
