on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./
